from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from ckeditor.fields import RichTextField



class Category(models.Model):
		title = models.CharField(max_length=100)

		def __str__(self):
				return self.title

		def get_absolute_url(self):
				return reverse("home")

	

class Company(models.Model):
		name = models.CharField(max_length=100)
		author = models.ForeignKey(User, on_delete = models.CASCADE) 
		breve = models.CharField(max_length=50)		
		description = RichTextField(blank=True,null=True)	
		#description = models.TextField(blank=True,max_length=2500)	
		email = models.EmailField(blank=True,)		
		website = models.URLField(blank=True,max_length=254,)
		phone = models.CharField(blank=True,max_length=30)	
		date_posted = models.DateTimeField(default = timezone.now)
		category = models.CharField(max_length=50, default="Uncategorized")	
		LOCATION = (('Afganistan', 'Afganistan'),
								('Albania', 'Albania'),
								('Algeria', 'Algeria'),
								('Angola', 'Angola'),
								('Anguilla', 'Anguilla'),
								('Argentina', 'Argentina'),
								('Armenia', 'Armenia'),
								('Australia', 'Australia'),
								('Austria', 'Austria'),
								('Azerbaijan', 'Azerbaijan'),
								('Bahrain', 'Bahrain'),
								('Bangladesh', 'Bangladesh'),
								('Belarus', 'Belarus'),
								('Belgium', 'Belgium'),
								('Belize', 'Belize'),
								('Benin', 'Benin'),
								('Bhutan', 'Bhutan'),
								('Bolivia', 'Bolivia'),
								('Bosnia & Herzegovina', 'Bosnia & Herzegovina'),
								('Botswana', 'Botswana'),
								('Brunei', 'Brunei'),
								('Bulgaria', 'Bulgaria'),
								('Burkina Faso', 'Burkina Faso'),
								('Cambodia', 'Cambodia'),
								('Cameroon', 'Cameroon'),
								('Canada', 'Canada'),
								('Central African Republic', 'Central African Republic'),
								('Chad', 'Chad'),
								('Chile', 'Chile'),
								('China', 'China'),
								('Colombia', 'Colombia'),
								('Congo', 'Congo'),
								('Costa Rica', 'Costa Rica'),
								('Cote DIvoire', 'Cote DIvoire'),
								('Croatia', 'Croatia'),
								('Cuba', 'Cuba'),
								('Curaco', 'Curaco'),
								('Cyprus', 'Cyprus'),
								('Czech Republic', 'Czech Republic'),
								('Denmark', 'Denmark'),
								('Dominica', 'Dominica'),
								('Dominican Republic', 'Dominican Republic'),
								('Ecuador', 'Ecuador'),
								('Egypt', 'Egypt'),
								('El Salvador', 'El Salvador'),
								('Equatorial Guinea', 'Equatorial Guinea'),
								('Eritrea', 'Eritrea'),
								('Estonia', 'Estonia'),
								('Ethiopia', 'Ethiopia'),
								('Finland', 'Finland'),
								('France', 'France'),
								('French Guiana', 'French Guiana'),
								('French Polynesia', 'French Polynesia'),
								('Gabon', 'Gabon'),
								('Gambia', 'Gambia'),
								('Georgia', 'Georgia'),
								('Germany', 'Germany'),
								('Ghana', 'Ghana'),
								('Gibraltar', 'Gibraltar'),
								('Great Britain', 'Great Britain'),
								('Greece', 'Greece'),
								('Grenada', 'Grenada'),
								('Guadeloupe', 'Guadeloupe'),
								('Guam', 'Guam'),
								('Guatemala', 'Guatemala'),
								('Guinea', 'Guinea'),
								('Haiti', 'Haiti'),
								('Honduras', 'Honduras'),
								('Hong Kong', 'Hong Kong'),
								('Hungary', 'Hungary'),
								('Iceland', 'Iceland'),
								('Indonesia', 'Indonesia'),
								('India', 'India'),
								('Iran', 'Iran'),
								('Iraq', 'Iraq'),
								('Ireland', 'Ireland'),
								('Israel', 'Israel'),
								('Italy', 'Italy'),
								('Jamaica', 'Jamaica'),
								('Japan', 'Japan'),
								('Jordan', 'Jordan'),
								('Kazakhstan', 'Kazakhstan'),
								('Kenya', 'Kenya'),
								('Korea South', 'Korea South'),
								('Kuwait', 'Kuwait'),
								('Kyrgyzstan', 'Kyrgyzstan'),
								('Laos', 'Laos'),
								('Latvia', 'Latvia'),
								('Lebanon', 'Lebanon'),
								('Lesotho', 'Lesotho'),
								('Liberia', 'Liberia'),
								('Libya', 'Libya'),
								('Liechtenstein', 'Liechtenstein'),
								('Lithuania', 'Lithuania'),
								('Luxembourg', 'Luxembourg'),
								('Macau', 'Macau'),
								('Macedonia', 'Macedonia'),
								('Madagascar', 'Madagascar'),
								('Malaysia', 'Malaysia'),
								('Malawi', 'Malawi'),
								('Mali', 'Mali'),
								('Malta', 'Malta'),
								('Martinique', 'Martinique'),
								('Mauritania', 'Mauritania'),
								('Mexico', 'Mexico'),
								('Moldova', 'Moldova'),
								('Monaco', 'Monaco'),
								('Mongolia', 'Mongolia'),
								('Montserrat', 'Montserrat'),
								('Morocco', 'Morocco'),
								('Mozambique', 'Mozambique'),
								('Myanmar', 'Myanmar'),
								('Nambia', 'Nambia'),
								('Nepal', 'Nepal'),
								('Netherlands', 'Netherlands'),
								('New Caledonia', 'New Caledonia'),
								('New Zealand', 'New Zealand'),
								('Nicaragua', 'Nicaragua'),
								('Niger', 'Niger'),
								('Nigeria', 'Nigeria'),
								('Norway', 'Norway'),
								('Oman', 'Oman'),
								('Pakistan', 'Pakistan'),
								('Palestine', 'Palestine'),
								('Panama', 'Panama'),
								('Papua New Guinea', 'Papua New Guinea'),
								('Paraguay', 'Paraguay'),
								('Peru', 'Peru'),
								('Phillipines', 'Phillipines'),
								('Poland', 'Poland'),
								('Portugal', 'Portugal'),
								('Puerto Rico', 'Puerto Rico'),
								('Qatar', 'Qatar'),
								('Republic of Montenegro', 'Republic of Montenegro'),
								('Republic of Serbia', 'Republic of Serbia'),
								('Romania', 'Romania'),
								('Russia', 'Russia'),
								('Rwanda', 'Rwanda'),
								('San Marino', 'San Marino'),
								('Saudi Arabia', 'Saudi Arabia'),
								('Senegal', 'Senegal'),
								('Sierra Leone', 'Sierra Leone'),
								('Singapore', 'Singapore'),
								('Slovakia', 'Slovakia'),
								('Slovenia', 'Slovenia'),
								('Somalia', 'Somalia'),
								('South Africa', 'South Africa'),
								('Spain', 'Spain'),
								('Sri Lanka', 'Sri Lanka'),
								('Sudan', 'Sudan'),
								('Suriname', 'Suriname'),
								('Swaziland', 'Swaziland'),
								('Switzerland', 'Switzerland'),
								('Syria', 'Syria'),
								('Taiwan', 'Taiwan'),
								('Tajikistan', 'Tajikistan'),
								('Tanzania', 'Tanzania'),
								('Thailand', 'Thailand'),
								('Togo', 'Togo'),
								('Tonga', 'Tonga'),
								('Tunisia', 'Tunisia'),
								('Turkey', 'Turkey'),
								('Turkmenistan', 'Turkmenistan'),
								('Uganda', 'Uganda'),
								('United Kingdom', 'United Kingdom'),
								('Ukraine', 'Ukraine'),
								('United Arab Erimates', 'United Arab Erimates'),
								('United States of America', 'United States of America'),
								('Uraguay', 'Uraguay'),
								('Uzbekistan', 'Uzbekistan'),
								('Venezuela', 'Venezuela'),
								('Vietnam', 'Vietnam'),
								('Yemen', 'Yemen'),
								('Zaire', 'Zaire'),
								('Zambia', 'Zambia'),
								('Zimbabwe', 'Zimbabwe'),)
		location = models.CharField(max_length = 100,choices=LOCATION, help_text="Select your Country.")

		def __str__(self):
				return self.name + " | " + str(self.author)

		def get_absolute_url(self):
				return reverse("company-detail", kwargs={"pk":self.pk})



#ADVERT


class AdvertCategory(models.Model):
		title = models.CharField(max_length=100)

		def __str__(self):
				return self.title

		def get_absolute_url(self):
				return reverse("home")

	

class Advert(models.Model):
		name = models.CharField(max_length=100)
		author = models.ForeignKey(User, on_delete = models.CASCADE) 
		breve = models.CharField(max_length=50)		
		description = RichTextField(blank=True,null=True)	
		#description = models.TextField(blank=True,max_length=2500)	
		email = models.EmailField(blank=True,)		
		website = models.URLField(blank=True,max_length=254,)
		phone = models.CharField(blank=True,max_length=30)	
		date_posted = models.DateTimeField(default = timezone.now)
		category = models.CharField(max_length=50, default="Uncategorized")	
		LOCATION = (('Afganistan', 'Afganistan'),
								('Albania', 'Albania'),
								('Algeria', 'Algeria'),
								('Angola', 'Angola'),
								('Anguilla', 'Anguilla'),
								('Argentina', 'Argentina'),
								('Armenia', 'Armenia'),
								('Australia', 'Australia'),
								('Austria', 'Austria'),
								('Azerbaijan', 'Azerbaijan'),
								('Bahrain', 'Bahrain'),
								('Bangladesh', 'Bangladesh'),
								('Belarus', 'Belarus'),
								('Belgium', 'Belgium'),
								('Belize', 'Belize'),
								('Benin', 'Benin'),
								('Bhutan', 'Bhutan'),
								('Bolivia', 'Bolivia'),
								('Bosnia & Herzegovina', 'Bosnia & Herzegovina'),
								('Botswana', 'Botswana'),
								('Brunei', 'Brunei'),
								('Bulgaria', 'Bulgaria'),
								('Burkina Faso', 'Burkina Faso'),
								('Cambodia', 'Cambodia'),
								('Cameroon', 'Cameroon'),
								('Canada', 'Canada'),
								('Central African Republic', 'Central African Republic'),
								('Chad', 'Chad'),
								('Chile', 'Chile'),
								('China', 'China'),
								('Colombia', 'Colombia'),
								('Congo', 'Congo'),
								('Costa Rica', 'Costa Rica'),
								('Cote DIvoire', 'Cote DIvoire'),
								('Croatia', 'Croatia'),
								('Cuba', 'Cuba'),
								('Curaco', 'Curaco'),
								('Cyprus', 'Cyprus'),
								('Czech Republic', 'Czech Republic'),
								('Denmark', 'Denmark'),
								('Dominica', 'Dominica'),
								('Dominican Republic', 'Dominican Republic'),
								('Ecuador', 'Ecuador'),
								('Egypt', 'Egypt'),
								('El Salvador', 'El Salvador'),
								('Equatorial Guinea', 'Equatorial Guinea'),
								('Eritrea', 'Eritrea'),
								('Estonia', 'Estonia'),
								('Ethiopia', 'Ethiopia'),
								('Finland', 'Finland'),
								('France', 'France'),
								('French Guiana', 'French Guiana'),
								('French Polynesia', 'French Polynesia'),
								('Gabon', 'Gabon'),
								('Gambia', 'Gambia'),
								('Georgia', 'Georgia'),
								('Germany', 'Germany'),
								('Ghana', 'Ghana'),
								('Gibraltar', 'Gibraltar'),
								('Great Britain', 'Great Britain'),
								('Greece', 'Greece'),
								('Grenada', 'Grenada'),
								('Guadeloupe', 'Guadeloupe'),
								('Guam', 'Guam'),
								('Guatemala', 'Guatemala'),
								('Guinea', 'Guinea'),
								('Haiti', 'Haiti'),
								('Honduras', 'Honduras'),
								('Hong Kong', 'Hong Kong'),
								('Hungary', 'Hungary'),
								('Iceland', 'Iceland'),
								('Indonesia', 'Indonesia'),
								('India', 'India'),
								('Iran', 'Iran'),
								('Iraq', 'Iraq'),
								('Ireland', 'Ireland'),
								('Israel', 'Israel'),
								('Italy', 'Italy'),
								('Jamaica', 'Jamaica'),
								('Japan', 'Japan'),
								('Jordan', 'Jordan'),
								('Kazakhstan', 'Kazakhstan'),
								('Kenya', 'Kenya'),
								('Korea South', 'Korea South'),
								('Kuwait', 'Kuwait'),
								('Kyrgyzstan', 'Kyrgyzstan'),
								('Laos', 'Laos'),
								('Latvia', 'Latvia'),
								('Lebanon', 'Lebanon'),
								('Lesotho', 'Lesotho'),
								('Liberia', 'Liberia'),
								('Libya', 'Libya'),
								('Liechtenstein', 'Liechtenstein'),
								('Lithuania', 'Lithuania'),
								('Luxembourg', 'Luxembourg'),
								('Macau', 'Macau'),
								('Macedonia', 'Macedonia'),
								('Madagascar', 'Madagascar'),
								('Malaysia', 'Malaysia'),
								('Malawi', 'Malawi'),
								('Mali', 'Mali'),
								('Malta', 'Malta'),
								('Martinique', 'Martinique'),
								('Mauritania', 'Mauritania'),
								('Mexico', 'Mexico'),
								('Moldova', 'Moldova'),
								('Monaco', 'Monaco'),
								('Mongolia', 'Mongolia'),
								('Montserrat', 'Montserrat'),
								('Morocco', 'Morocco'),
								('Mozambique', 'Mozambique'),
								('Myanmar', 'Myanmar'),
								('Nambia', 'Nambia'),
								('Nepal', 'Nepal'),
								('Netherlands', 'Netherlands'),
								('New Caledonia', 'New Caledonia'),
								('New Zealand', 'New Zealand'),
								('Nicaragua', 'Nicaragua'),
								('Niger', 'Niger'),
								('Nigeria', 'Nigeria'),
								('Norway', 'Norway'),
								('Oman', 'Oman'),
								('Pakistan', 'Pakistan'),
								('Palestine', 'Palestine'),
								('Panama', 'Panama'),
								('Papua New Guinea', 'Papua New Guinea'),
								('Paraguay', 'Paraguay'),
								('Peru', 'Peru'),
								('Phillipines', 'Phillipines'),
								('Poland', 'Poland'),
								('Portugal', 'Portugal'),
								('Puerto Rico', 'Puerto Rico'),
								('Qatar', 'Qatar'),
								('Republic of Montenegro', 'Republic of Montenegro'),
								('Republic of Serbia', 'Republic of Serbia'),
								('Romania', 'Romania'),
								('Russia', 'Russia'),
								('Rwanda', 'Rwanda'),
								('San Marino', 'San Marino'),
								('Saudi Arabia', 'Saudi Arabia'),
								('Senegal', 'Senegal'),
								('Sierra Leone', 'Sierra Leone'),
								('Singapore', 'Singapore'),
								('Slovakia', 'Slovakia'),
								('Slovenia', 'Slovenia'),
								('Somalia', 'Somalia'),
								('South Africa', 'South Africa'),
								('Spain', 'Spain'),
								('Sri Lanka', 'Sri Lanka'),
								('Sudan', 'Sudan'),
								('Suriname', 'Suriname'),
								('Swaziland', 'Swaziland'),
								('Switzerland', 'Switzerland'),
								('Syria', 'Syria'),
								('Taiwan', 'Taiwan'),
								('Tajikistan', 'Tajikistan'),
								('Tanzania', 'Tanzania'),
								('Thailand', 'Thailand'),
								('Togo', 'Togo'),
								('Tonga', 'Tonga'),
								('Tunisia', 'Tunisia'),
								('Turkey', 'Turkey'),
								('Turkmenistan', 'Turkmenistan'),
								('Uganda', 'Uganda'),
								('United Kingdom', 'United Kingdom'),
								('Ukraine', 'Ukraine'),
								('United Arab Erimates', 'United Arab Erimates'),
								('United States of America', 'United States of America'),
								('Uraguay', 'Uraguay'),
								('Uzbekistan', 'Uzbekistan'),
								('Venezuela', 'Venezuela'),
								('Vietnam', 'Vietnam'),
								('Yemen', 'Yemen'),
								('Zaire', 'Zaire'),
								('Zambia', 'Zambia'),
								('Zimbabwe', 'Zimbabwe'),)
		location = models.CharField(max_length = 100,choices=LOCATION, help_text="Select your Country.")

		def __str__(self):
				return self.name + " | " + str(self.author)

		def get_absolute_url(self):
				return reverse("advert-detail", kwargs={"pk":self.pk})

