# Generated by Django 2.2.4 on 2020-08-10 18:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0003_auto_20200809_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
